import {
  Baby,
  BookOpen,
  Church,
  Drama,
  Droplets,
  Dumbbell,
  Flower2,
  GraduationCap,
  Landmark,
  LayoutGrid,
  Leaf,
  MapPin,
  School,
  ShoppingBag,
  ShoppingCart,
  Trees,
  Umbrella,
  Users,
  Waves,
  X,
  type LucideIcon,
} from 'lucide-react';

export const ICON_COMPONENTS: Record<string, LucideIcon> = {
  baby: Baby,
  'book-open': BookOpen,
  church: Church,
  drama: Drama,
  droplets: Droplets,
  dumbbell: Dumbbell,
  'flower-2': Flower2,
  'graduation-cap': GraduationCap,
  landmark: Landmark,
  'layout-grid': LayoutGrid,
  leaf: Leaf,
  'map-pin': MapPin,
  school: School,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  trees: Trees,
  umbrella: Umbrella,
  users: Users,
  waves: Waves,
  x: X,
};
